# Generated by Django 4.1 on 2022-08-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_news_tag_news_tags_news_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tags_news',
            new_name='tag_news',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='tag',
            new_name='tags',
        ),
    ]
